import tempfile
from datetime import datetime
from typing import List, Optional
from fastapi import APIRouter, Query, HTTPException
from fastapi.responses import FileResponse
from fpdf import FPDF

from app.core.explorer_data import LOCATIONS, generate_unified_climate_model, find_location

router = APIRouter()

class ExplorerReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(14, 165, 233)  # Sky blue
        self.cell(0, 10, "CLIMATETWIN INDIA - REGIONAL CLIMATE INTELLIGENCE REPORT", border=0, align="L")
        self.set_draw_color(14, 165, 233)
        self.line(10, 20, 200, 20)
        self.ln(12)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} (IST)", border=0, align="C")

@router.get("/climate/explorer/locations")
async def get_explorer_locations():
    return [
        {
            "state": l["state"],
            "district": l["district"],
            "city": l["city"],
            "lat": l["lat"],
            "lng": l["lng"]
        } for l in LOCATIONS
    ]

@router.get("/climate/explorer/data")
async def get_explorer_data(
    state: Optional[str] = Query(None),
    district: Optional[str] = Query(None),
    city: Optional[str] = Query(None)
):
    try:
        data = generate_unified_climate_model(state, district, city)
        return data
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate climate model: {str(e)}")

@router.get("/climate/explorer/report")
async def get_explorer_report(
    state: Optional[str] = Query(None),
    district: Optional[str] = Query(None),
    city: Optional[str] = Query(None)
):
    loc = find_location(state, district, city)
    data = generate_unified_climate_model(state, district, city)
    
    current = data["current"]
    forecast = data["forecast"]
    trends = data["trends"]
    risks = data["disasterRisk"]
    summary = data["aiSummary"]

    pdf = ExplorerReportPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(51, 65, 85) # Slate-700

    # 1. Title Block
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, f"Climate Profile: {loc['city']}, {loc['state']}", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, f"This document represents the unified Climate Explorer & Forecast Intelligence report generated by ClimateTwin India's spatial twin models. Telemetry data is merged across INSAT satellite feeds, CPCB AQI trackers, and regional IMD meteorological advisories.")
    pdf.ln(4)

    # 2. Location Metadata Table
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Geographical Information", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_fill_color(241, 245, 249) # Slate-100
    
    pdf.cell(45, 8, "State", border=1, fill=True)
    pdf.cell(50, 8, loc["state"], border=1)
    pdf.cell(45, 8, "District", border=1, fill=True)
    pdf.cell(50, 8, loc["district"], border=1, ln=True)
    
    pdf.cell(45, 8, "Latitude", border=1, fill=True)
    pdf.cell(50, 8, f"{loc['lat']:.4f} N", border=1)
    pdf.cell(45, 8, "Longitude", border=1, fill=True)
    pdf.cell(50, 8, f"{loc['lng']:.4f} E", border=1, ln=True)
    
    pdf.cell(45, 8, "Elevation", border=1, fill=True)
    pdf.cell(50, 8, f"{loc['elev']} meters", border=1)
    pdf.cell(45, 8, "Climatic Zone", border=1, fill=True)
    pdf.cell(50, 8, loc["zone"].upper(), border=1, ln=True)
    pdf.ln(6)

    # 3. Current Climate Metrics Table
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Current Climate Telemetry", ln=True)
    pdf.set_font("Helvetica", "", 9)
    
    # Header
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(45, 6, "Metric", border=1, fill=True)
    pdf.cell(50, 6, "Value", border=1, fill=True)
    pdf.cell(45, 6, "Metric", border=1, fill=True)
    pdf.cell(50, 6, "Value", border=1, fill=True, ln=True)
    pdf.set_font("Helvetica", "", 9)

    metrics_list = [
        ("Temperature", f"{current['temperature']} C (Feels: {current['feelsLike']} C)", "Min / Max Temp", f"{current['minTemp']} C / {current['maxTemp']} C"),
        ("Humidity", f"{current['humidity']}%", "Rainfall (24h)", f"{current['rainfall']} mm"),
        ("Wind Speed/Dir", f"{current['windSpeed']} km/h ({current['windDirection']})", "Air Pressure", f"{current['airPressure']} hPa"),
        ("Visibility", f"{current['visibility']} km", "UV Index", f"{current['uvIndex']}"),
        ("Cloud Cover", f"{current['cloudCover']}%", "Air Quality Index (AQI)", f"{current['aqi']}"),
        ("Soil Moisture", f"{current['soilMoisture'] if current['soilMoisture'] is not None else 'N/A'}", "Condition", f"{current['condition'].upper()}"),
    ]

    for m1, v1, m2, v2 in metrics_list:
        pdf.cell(45, 6, m1, border=1)
        pdf.cell(50, 6, v1, border=1)
        pdf.cell(45, 6, m2, border=1)
        pdf.cell(50, 6, v2, border=1, ln=True)
    pdf.ln(6)

    # 4. AI Climate Summary
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "AI Climate Summary", ln=True)
    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(30, 41, 59) # Slate-800
    pdf.multi_cell(0, 6, f"\"{summary}\"")
    pdf.set_text_color(51, 65, 85) # Reset
    pdf.ln(6)

    # 5. Predictions & Forecasts
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "AI-Based Weather Forecast (Next 7 Days)", ln=True)
    pdf.set_font("Helvetica", "B", 9)
    
    # Table headers
    pdf.cell(30, 6, "Date", border=1, fill=True)
    pdf.cell(30, 6, "Max / Min Temp", border=1, fill=True)
    pdf.cell(30, 6, "Rain Prob (%)", border=1, fill=True)
    pdf.cell(30, 6, "Rainfall (mm)", border=1, fill=True)
    pdf.cell(35, 6, "Humidity (%)", border=1, fill=True)
    pdf.cell(35, 6, "Condition", border=1, fill=True, ln=True)
    pdf.set_font("Helvetica", "", 9)

    for day in forecast["daily"][:7]:
        pdf.cell(30, 6, day["date"], border=1)
        pdf.cell(30, 6, f"{day['maxTemp']} C / {day['minTemp']} C", border=1)
        pdf.cell(30, 6, f"{day['rainProbability']:.0f}%", border=1)
        pdf.cell(30, 6, f"{day['rainfall']:.1f} mm", border=1)
        pdf.cell(35, 6, f"{day['humidity']:.0f}%", border=1)
        pdf.cell(35, 6, day["condition"].upper(), border=1, ln=True)
    
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 6, f"Confidence & Accuracy: Forecast models indicate an accuracy probability of {forecast['forecastAccuracy']}% using Prophet/LSTM ensembles.", ln=True)
    pdf.ln(6)

    # Page Break for Trends & Risks
    pdf.add_page()
    
    # 6. Long Term Trends
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Long-Term Climate Trend Analysis", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"* warming Rate: +{trends['warmingRateDecade']:.3f} C per decade.", ln=True)
    pdf.cell(0, 6, f"* Extreme Heat Days Trend: {trends['extremeHeatDaysTrend']}.", ln=True)
    pdf.cell(0, 6, f"* Monsoon Progression Trend: {trends['monsoonOnsetTrend']}.", ln=True)
    pdf.cell(0, 6, f"* Current Year Annual Rainfall Anomaly: {trends['annualRainfallAnomaly']} mm vs 30-year average.", ln=True)
    pdf.ln(6)

    # 7. Disaster Risk Profile
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "AI Disaster Risk Intelligence & Hazard Matrix", ln=True)
    pdf.set_font("Helvetica", "B", 9)
    
    pdf.cell(40, 6, "Hazard Risk", border=1, fill=True)
    pdf.cell(30, 6, "Risk Level", border=1, fill=True)
    pdf.cell(30, 6, "Probability", border=1, fill=True)
    pdf.cell(45, 6, "Severity Score (0-10)", border=1, fill=True)
    pdf.cell(45, 6, "Confidence Score", border=1, fill=True, ln=True)
    pdf.set_font("Helvetica", "", 9)

    if not risks["activeAlerts"]:
        pdf.cell(190, 6, "No severe active climate hazard risk zones identified.", border=1, ln=True, align="C")
    else:
        for alert in risks["activeAlerts"][:5]:
            pdf.cell(40, 6, alert["hazard"].replace("_", " ").upper(), border=1)
            pdf.cell(30, 6, alert["riskLevel"].upper(), border=1)
            pdf.cell(30, 6, f"{alert['probability']:.1f}%", border=1)
            pdf.cell(45, 6, f"{alert['severityScore']}/10", border=1)
            pdf.cell(45, 6, f"{alert['confidenceScore']}%", border=1, ln=True)

    pdf.ln(6)
    
    if risks["activeAlerts"]:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "Critical Public Safety Recommendations:", ln=True)
        pdf.set_font("Helvetica", "", 9)
        for alert in risks["activeAlerts"][:2]:
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 5, f"- {alert['hazard'].replace('_', ' ').upper()}:", ln=True)
            pdf.set_font("Helvetica", "", 9)
            for precaution in alert["precautions"][:3]:
                pdf.cell(10)
                pdf.cell(0, 5, f"* {precaution}", ln=True)
                
    # Save PDF to temporary file
    fd, path = tempfile.mkstemp(suffix=".pdf")
    pdf.output(path)
    
    # Return file response
    filename = f"ClimateTwin_Report_{loc['city'].replace(' ', '_')}_{datetime.now().strftime('%Y%m%d')}.pdf"
    return FileResponse(
        path,
        media_type="application/pdf",
        filename=filename
    )
