import tempfile
from datetime import datetime
from fastapi import APIRouter, Query
from fastapi.responses import FileResponse
from fpdf import FPDF

router = APIRouter()

class ReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(14, 165, 233) # Sky blue
        self.cell(0, 10, "CLIMATETWIN INDIA - EXECUTIVE SIMULATION REPORT", border=0, align="L")
        self.set_draw_color(14, 165, 233)
        self.line(10, 20, 200, 20)
        self.ln(12)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", border=0, align="C")

@router.get("/reports/download")
async def download_report(
    temperatureChange: float = Query(0.0),
    rainfallChange: float = Query(0.0),
    deforestationPercent: float = Query(0.0),
    urbanExpansionPercent: float = Query(0.0),
    seaLevelRise: float = Query(0.0),
    carbonEmissionsChange: float = Query(0.0)
):
    # Perform math calculations (matching scenarios.py)
    base_flood_risk = 38.0
    base_drought_risk = 30.0
    base_heatwave_risk = 45.0

    flood_inc = rainfallChange * 0.8 if rainfallChange > 0 else rainfallChange * 0.3
    flood_risk = min(100.0, max(0.0, base_flood_risk + flood_inc + seaLevelRise * 12.0 + deforestationPercent * 0.6 + urbanExpansionPercent * 0.4))
    
    drought_inc = abs(rainfallChange) * 0.9 if rainfallChange < 0 else -rainfallChange * 0.3
    drought_risk = min(100.0, max(0.0, base_drought_risk + drought_inc + temperatureChange * 3.5 + deforestationPercent * 0.5))

    heat_dec = rainfallChange * 0.2 if rainfallChange > 0 else 0.0
    heatwave_risk = min(100.0, max(0.0, base_heatwave_risk + temperatureChange * 8.0 + urbanExpansionPercent * 0.7 + carbonEmissionsChange * 0.2 - heat_dec - (deforestationPercent * 0.1)))

    agri_impact = min(100.0, max(-100.0, -(temperatureChange * 6.0) + (rainfallChange * 0.5) - (deforestationPercent * 1.2) - (drought_risk - base_drought_risk) * 0.4))
    water_avail = min(50.0, max(-70.0, rainfallChange * 0.6 - temperatureChange * 4.0 - deforestationPercent * 0.8 - urbanExpansionPercent * 0.5 + seaLevelRise * (-5.0)))
    
    affected_pop = int(round((flood_risk * 4.2 + drought_risk * 3.8 + heatwave_risk * 5.1) / 3.0 * 0.8))
    def_co2 = abs(deforestationPercent) * 1.5 if deforestationPercent < 0 else deforestationPercent * 2.0
    co2_con = 422.6 + carbonEmissionsChange * 0.8 - def_co2
    surf_temp = 34.2 + temperatureChange + urbanExpansionPercent * 0.05 + carbonEmissionsChange * 0.02

    # UHI Index
    uhi_index = max(1.0, min(10.0, 5.0 + (urbanExpansionPercent * 0.15) - (deforestationPercent * 0.05) + (temperatureChange * 0.2)))

    # Generate PDF
    pdf = ReportPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(51, 65, 85) # Slate-700

    # Summary Intro
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Digital Twin Simulation Summary", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, "This document presents the environmental impact assessment generated by the ClimateTwin India simulation engine. The digital twin models regional risks based on the specified parameters of global warming, forest cover changes, urban growth, and emissions trajectories.")
    pdf.ln(5)

    # 1. Inputs Section
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "1. Input Simulation Parameters", ln=True)
    pdf.set_font("Helvetica", "", 10)
    
    # Render table of inputs
    pdf.set_fill_color(241, 245, 249) # Slate-100
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(90, 8, "Parameter Name", border=1, fill=True)
    pdf.cell(90, 8, "Value Selected", border=1, fill=True, ln=True)
    pdf.set_font("Helvetica", "", 10)

    inputs_list = [
        ("Temperature Deviation", f"{temperatureChange:+.1f} C"),
        ("Rainfall Shift", f"{rainfallChange:+.1f}%"),
        ("Deforestation Rate", f"{deforestationPercent:.1f}%"),
        ("Urban Sprawl Expansion", f"{urbanExpansionPercent:.1f}%"),
        ("Sea-Level Elevation Rise", f"{seaLevelRise:.2f} meters"),
        ("Carbon Emission Variance", f"{carbonEmissionsChange:+.1f}%"),
    ]

    for param, val in inputs_list:
        pdf.cell(90, 8, param, border=1)
        pdf.cell(90, 8, val, border=1, ln=True)
    pdf.ln(8)

    # 2. Outputs Section
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "2. Projected Climate & Hazards Impact", ln=True)
    pdf.set_font("Helvetica", "", 10)
    
    # Render table of outputs
    pdf.set_fill_color(241, 245, 249)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(90, 8, "Impact Indicator", border=1, fill=True)
    pdf.cell(90, 8, "Projected Outcome", border=1, fill=True, ln=True)
    pdf.set_font("Helvetica", "", 10)

    outputs_list = [
        ("Surface Temperature Average", f"{surf_temp:.1f} C"),
        ("Carbon Dioxide Concentration", f"{co2_con:.1f} ppm"),
        ("Urban Heat Island (UHI) Index", f"{uhi_index:.1f} / 10"),
        ("Flood Susceptibility Risk", f"{flood_risk:.1f}%"),
        ("Drought Susceptibility Risk", f"{drought_risk:.1f}%"),
        ("Heatwave Severity Risk", f"{heatwave_risk:.1f}%"),
        ("Agricultural Yield Variance", f"{agri_impact:+.1f}%"),
        ("Water Reservoirs Availability", f"{water_avail:+.1f}%"),
        ("Estimated Population At Risk", f"{affected_pop:,} million people"),
    ]

    for metric, val in outputs_list:
        pdf.cell(90, 8, metric, border=1)
        pdf.cell(90, 8, val, border=1, ln=True)
    pdf.ln(10)

    # 3. Policy Recommendations
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "3. Recommedations & Mitigation Strategy", ln=True)
    pdf.set_font("Helvetica", "", 10)
    
    analysis_text = ""
    if uhi_index > 6.0:
        analysis_text += "* Urban Heat Island effect is CRITICAL. Cities should immediately mandate cool roofing policies and increase green cover by at least 15%.\n"
    if flood_risk > 50.0:
        analysis_text += "* Flood Risk is HIGH. Districts along major river basin catchments must reinforce check-dams and prepare low-lying zone evacuations.\n"
    if agri_impact < -10.0:
        analysis_text += "* Crop yields are severely threatened. Advise transition to drought-resistant millets (Bajra/Ragi) and adopt micro-sprinklers.\n"
    if water_avail < -15.0:
        analysis_text += "* Severe aquifer stress predicted. Implement artificial groundwater recharging structures and limit heavy-outflow cropping (e.g. sugarcane).\n"
    
    if not analysis_text:
        analysis_text = "* Environmental variables remain within historical baselines. Continue standard watershed management and periodic observation."

    pdf.multi_cell(0, 6, analysis_text)

    # Save to a temporary file
    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    pdf.output(temp_file.name)
    temp_file.close()

    return FileResponse(
        temp_file.name,
        media_type="application/pdf",
        filename=f"climatetwin_simulation_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    )
